"""Alpha 7 LYF plus the separately maintained v6 compatibility executor."""

from importlib.metadata import PackageNotFoundError, version

from .ast import (
    AgentDecorator,
    AssignmentStatement,
    AwaitExpr,
    BinaryExpr,
    BindingStatement,
    CallExpr,
    Decorator,
    DecoratorArgument,
    DiscardTarget,
    EventsDecorator,
    ExpressionStatement,
    FunctionDeclaration,
    FunctionProgram,
    IndexExpr,
    ListExpr,
    LiteralExpr,
    MemberExpr,
    NameExpr,
    NameTarget,
    ObjectEntry,
    ObjectExpr,
    PassStatement,
    ReturnStatement,
    SourcePosition,
    SourceSpan,
    TupleExpr,
    TupleTarget,
    UnaryExpr,
    UnknownDecorator,
    UnsupportedStatement,
    UseDeclaration,
)
from .diagnostics import Diagnostic, ParseResult
from .executor import (
    V6FunctionCapabilityError,
    V6FunctionExecutor,
    V6FunctionRuntimeError,
    V6FunctionSyntaxError,
)
from .host import Alpha7FunctionHost, Alpha7FunctionHostProvider, FunctionHostError, host_provider
from .libraries import (
    FUNCTION_LIBRARY_ENTRY_POINT_GROUP,
    FunctionContext,
    LibraryDefinition,
    LibraryExport,
    LibraryRegistry,
    default_library_definitions,
    default_library_registry,
)
from .parser import parse
from .preflight import EventContribution, PreflightResult, PromptContribution, ToolContribution, preflight
from .runtime import FunctionRuntime, FunctionRuntimeError

try:
    __version__ = version("liteyukibot-v7-functions")
except PackageNotFoundError:
    __version__ = "0.1.0a3"

__all__ = [
    "AgentDecorator",
    "AssignmentStatement",
    "AwaitExpr",
    "BinaryExpr",
    "BindingStatement",
    "CallExpr",
    "Decorator",
    "DecoratorArgument",
    "Diagnostic",
    "DiscardTarget",
    "EventContribution",
    "EventsDecorator",
    "ExpressionStatement",
    "FUNCTION_LIBRARY_ENTRY_POINT_GROUP",
    "FunctionContext",
    "Alpha7FunctionHost",
    "Alpha7FunctionHostProvider",
    "FunctionHostError",
    "FunctionDeclaration",
    "FunctionProgram",
    "V6FunctionCapabilityError",
    "V6FunctionExecutor",
    "V6FunctionRuntimeError",
    "V6FunctionSyntaxError",
    "FunctionRuntime",
    "FunctionRuntimeError",
    "IndexExpr",
    "LibraryDefinition",
    "LibraryExport",
    "LibraryRegistry",
    "ListExpr",
    "LiteralExpr",
    "MemberExpr",
    "NameExpr",
    "NameTarget",
    "ObjectEntry",
    "ObjectExpr",
    "ParseResult",
    "PassStatement",
    "PreflightResult",
    "PromptContribution",
    "ReturnStatement",
    "SourcePosition",
    "SourceSpan",
    "ToolContribution",
    "TupleExpr",
    "TupleTarget",
    "UnaryExpr",
    "UnknownDecorator",
    "UnsupportedStatement",
    "UseDeclaration",
    "default_library_registry",
    "default_library_definitions",
    "host_provider",
    "parse",
    "preflight",
    "__version__",
]
