name: 发布资源
title: "Resource: {name}"
description: 发布资源到轻雪机器人官方商店
labels: [ "Resource" ]
body:
  - type: input
    id: name
    attributes:
      label: 名称
      description: 资源包的可读名称
      placeholder: e.g. 可爱UI资源包
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: 描述
      description: 资源的简短描述
      placeholder: e.g. 使渲染卡片的样式更美观
    validations:
      required: true

  - type: input
    id: author
    attributes:
      label: 作者
      description: 作者的github用户名
      placeholder: e.g. snowykami
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: 下载链接
      description: 资源包直接下载链接
      placeholder: e.g. https://aaa.com/r.zip
    validations:
      required: true

  - type: input
    id: homepage
    attributes:
      label: 主页
      description: 资源包主页
      placeholder: e.g. https://github.com/user/repo
    validations:
      required: false

  - type: input
    id: tags
    attributes:
      label: 标签
      description: 标签
      placeholder: 'e.g. [{"label": "标签名", "color": "#ea5252"}]'
      value: '[ { "label": "标签名", "color": "#a2d8f4" } ]'
    validations:
      required: false
