name: Publish Resource
title: "Resource: {name}"
description: Publish the resource to the LiteyukiBot official store
labels: [ "Resource" ]
body:
  - type: input
    id: name
    attributes:
      label: Name
      description: The readable name of the resource pack
      placeholder: e.g. Cute UI Resource Pack
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: Description
      description: A brief description of the resource
      placeholder: e.g. Makes the rendering card style more beautiful
    validations:
      required: true

  - type: input
    id: author
    attributes:
      label: Author
      description: The GitHub username of the author
      placeholder: e.g. snowykami
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Link
      description: Direct download link of the resource pack
      placeholder: e.g. https://aaa.com/r.zip
    validations:
      required: true

  - type: input
    id: homepage
    attributes:
      label: Homepage
      description: Homepage of the resource pack
      placeholder: e.g. https://github.com/user/repo
    validations:
      required: false

  - type: input
    id: tags
    attributes:
      label: Tags
      description: Tags
      placeholder: 'e.g. [{"label": "Tag Name", "color": "#ea5252"}]'
      value: '[ { "label": "Text", "color": "#a2d8f4" } ]'
    validations:
      required: false
