from typing import Self

LYIP_NATIVE_ABI: int
native_available: bool

class SharedSpscRing:
    def __init__(self, name: str, capacity: int, slot_size: int) -> None: ...
    @classmethod
    def open(cls, name: str) -> Self: ...
    @property
    def name(self) -> str: ...
    @property
    def capacity(self) -> int: ...
    @property
    def slot_size(self) -> int: ...
    def try_push(self, payload: bytes) -> bool: ...
    def try_pop(self) -> bytes | None: ...
