nonebot:
  host: 0.0.0.0
  port: 20216
  command_start: ["", "/"]
  nickname: [ "liteyuki" ]
  default_language: zh
  driver: ~fastapi+~httpx+~websockets
  alconna_use_command_start: true
  gotify_token: "empty token"

