"""Broker-side bridge registration primitives.

This is the v6 broker migration entry point. It is intentionally not
interoperable with the legacy runtime child protocol.
"""

from .actions import (
    MESSAGE_SEND_KIND,
    MessageSendPayload,
    make_message_send_request,
    message_send_resource_key,
    parse_message_send_request,
)
from .business import (
    BROKER_ACTION_REQUEST_TYPE_ID,
    BROKER_ACTION_RESULT_TYPE_ID,
    BROKER_EVENT_ACCEPTED_TYPE_ID,
    BROKER_EVENT_COMPLETED_TYPE_ID,
    BROKER_EVENT_INGRESS_TYPE_ID,
    BROKER_EVENT_MESSAGE_TYPE_ID,
    BrokerBusinessWireError,
    decode_business_message,
    encode_business_message,
)
from .host import ActionOutcome, BrokerBridgeRunner, BrokerDelivery
from .kernel import KernelBridgeError, KernelBrokerPeer, configured_kernel_bridge
from .peer import (
    BridgeClient,
    BridgeRegistrationError,
    BridgeSession,
    BrokerPeerServer,
    BrokerPeerService,
    BusinessDispatch,
)
from .protocol import (
    BROKER_PROTOCOL_VERSION,
    ActionResourceDeclaration,
    BridgeAccess,
    BridgeManifest,
    BridgeRegister,
    BridgeRegistered,
    BridgeRejected,
    BridgeUnregister,
    BridgeUnregistered,
    BrokerWireError,
    decode_broker_message,
    encode_broker_message,
)
from .routing import (
    ActionRequest,
    ActionResult,
    BrokerAdmissionError,
    BrokerEvent,
    BrokerLedger,
    DeliverySnapshot,
    DeliveryState,
    EventAccepted,
    EventCompleted,
    EventIngress,
    EventMessage,
    EventSnapshot,
    RoutedAction,
)
from .service import BridgeCatalog, BridgeLauncher, BrokerService, bridge_token_from_vault

__all__ = [
    "BROKER_PROTOCOL_VERSION",
    "MESSAGE_SEND_KIND",
    "BROKER_ACTION_REQUEST_TYPE_ID",
    "BROKER_ACTION_RESULT_TYPE_ID",
    "BROKER_EVENT_ACCEPTED_TYPE_ID",
    "BROKER_EVENT_COMPLETED_TYPE_ID",
    "BROKER_EVENT_INGRESS_TYPE_ID",
    "BROKER_EVENT_MESSAGE_TYPE_ID",
    "ActionRequest",
    "ActionOutcome",
    "ActionResourceDeclaration",
    "ActionResult",
    "BridgeAccess",
    "BridgeClient",
    "BrokerBridgeRunner",
    "BrokerDelivery",
    "KernelBridgeError",
    "KernelBrokerPeer",
    "BridgeManifest",
    "BridgeRegister",
    "BridgeRegistered",
    "BridgeRegistrationError",
    "BridgeRejected",
    "BridgeSession",
    "BridgeUnregister",
    "BridgeUnregistered",
    "BusinessDispatch",
    "BrokerAdmissionError",
    "BrokerBusinessWireError",
    "BrokerEvent",
    "BrokerLedger",
    "BrokerPeerServer",
    "BrokerPeerService",
    "BrokerWireError",
    "BrokerService",
    "BridgeCatalog",
    "BridgeLauncher",
    "DeliverySnapshot",
    "DeliveryState",
    "EventIngress",
    "EventAccepted",
    "EventCompleted",
    "EventMessage",
    "EventSnapshot",
    "MessageSendPayload",
    "RoutedAction",
    "decode_broker_message",
    "decode_business_message",
    "encode_business_message",
    "encode_broker_message",
    "bridge_token_from_vault",
    "configured_kernel_bridge",
    "make_message_send_request",
    "message_send_resource_key",
    "parse_message_send_request",
]
