"""Broker-side bridge registration primitives.

This is the v6 broker migration entry point. It is intentionally not
interoperable with the legacy runtime child protocol.
"""

from .business import (
    BROKER_ACTION_REQUEST_TYPE_ID,
    BROKER_ACTION_RESULT_TYPE_ID,
    BROKER_EVENT_ACCEPTED_TYPE_ID,
    BROKER_EVENT_COMPLETED_TYPE_ID,
    BROKER_EVENT_INGRESS_TYPE_ID,
    BROKER_EVENT_MESSAGE_TYPE_ID,
    BrokerBusinessWireError,
    decode_business_message,
    encode_business_message,
)
from .peer import (
    BridgeClient,
    BridgeRegistrationError,
    BridgeSession,
    BrokerPeerServer,
    BrokerPeerService,
    BusinessDispatch,
)
from .protocol import (
    BROKER_PROTOCOL_VERSION,
    ActionResourceDeclaration,
    BridgeAccess,
    BridgeManifest,
    BridgeRegister,
    BridgeRegistered,
    BridgeRejected,
    BridgeUnregister,
    BridgeUnregistered,
    BrokerWireError,
    decode_broker_message,
    encode_broker_message,
)
from .routing import (
    ActionRequest,
    ActionResult,
    BrokerAdmissionError,
    BrokerEvent,
    BrokerLedger,
    DeliverySnapshot,
    DeliveryState,
    EventAccepted,
    EventCompleted,
    EventIngress,
    EventMessage,
    EventSnapshot,
    RoutedAction,
)

__all__ = [
    "BROKER_PROTOCOL_VERSION",
    "BROKER_ACTION_REQUEST_TYPE_ID",
    "BROKER_ACTION_RESULT_TYPE_ID",
    "BROKER_EVENT_ACCEPTED_TYPE_ID",
    "BROKER_EVENT_COMPLETED_TYPE_ID",
    "BROKER_EVENT_INGRESS_TYPE_ID",
    "BROKER_EVENT_MESSAGE_TYPE_ID",
    "ActionRequest",
    "ActionResourceDeclaration",
    "ActionResult",
    "BridgeAccess",
    "BridgeClient",
    "BridgeManifest",
    "BridgeRegister",
    "BridgeRegistered",
    "BridgeRegistrationError",
    "BridgeRejected",
    "BridgeSession",
    "BridgeUnregister",
    "BridgeUnregistered",
    "BusinessDispatch",
    "BrokerAdmissionError",
    "BrokerBusinessWireError",
    "BrokerEvent",
    "BrokerLedger",
    "BrokerPeerServer",
    "BrokerPeerService",
    "BrokerWireError",
    "DeliverySnapshot",
    "DeliveryState",
    "EventIngress",
    "EventAccepted",
    "EventCompleted",
    "EventMessage",
    "EventSnapshot",
    "RoutedAction",
    "decode_broker_message",
    "decode_business_message",
    "encode_business_message",
    "encode_broker_message",
]
