name: Liteyuki PyPI Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  liteyuki-pypi-publish:
    name: upload release to PyPI (Nightly)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - uses: pdm-project/setup-pdm@v3

      - name: Publish package distributions to PyPI
        run: pdm publish